"""add_qa_doc

Revision ID: b2d5d90a7d8b
Revises: 4bcffcd64aa4
Create Date: 2023-09-02 22:32:21.863998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2d5d90a7d8b'
down_revision = '4bcffcd64aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_qa_document',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('app_id', postgresql.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='app_qa_document_pkey')
    )
    with op.batch_alter_table('app_qa_document', schema=None) as batch_op:
        batch_op.create_index('app_qa_document_app_idx', ['app_id'], unique=False)

    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=255), server_default=sa.text("'text-embedding-ada-002'::character varying"), nullable=True))
        batch_op.add_column(sa.Column('embedding_model_provider', sa.String(length=255), server_default=sa.text("'openai'::character varying"), nullable=True))
        batch_op.add_column(sa.Column('qa_index_struct', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_model_configs', schema=None) as batch_op:
        batch_op.drop_column('qa_index_struct')
        batch_op.drop_column('embedding_model_provider')
        batch_op.drop_column('embedding_model')

    with op.batch_alter_table('app_qa_document', schema=None) as batch_op:
        batch_op.drop_index('app_qa_document_app_idx')

    op.drop_table('app_qa_document')
    # ### end Alembic commands ###
